src/assets/content.js
src/components/Overlay/OverlayDescription/index.js
src/components/Overlay/OverlayTop/index.js
src/components/Sidebar/SidebarAbout/index.js

This PR updates the info texts and the wording of some elements.
The suggested changes (in the Google Doc) concerning renaming the overlay buttons were not implemented, because the phrase "Konto anlegen" would exclude people logging in.

Update info texts

---

src/components/AppWrapper/index.js
src/components/Credits/index.js
src/components/Overlay/OverlayBottom/index.js
src/components/Sidebar/SidebarAbout/index.js

This PR creates a _Credits_ component for the the logos and displays it according to the screen width in either:
- the top right corner of the map
- or inside the infobox

Hide logos on mobile

---

src/assets/content.js
src/components/Sidebar/SidebarProfile/index.js

This PR fixes two small typos:
- in overlay: "Ihnen" -> "ihnen"
- in profile: "unwiederruflich" -> "unwiderruflich"

fix: typos in overlay and profile

---

src/assets/content.js

This PR 
- adds the correct note for data provenance at the bottom of the sidebar
- removes the "Plattform und Daten" section in the sidebar
Fixes #94 
Also fixes #42

fix: include correct data provenance section

---

src/components/Card/CardAccordion/TreesAdopted.js

This PR fixes #162 by exchanging latitude and longitude when selecting an adopted tree from the user's sidebar.
**But**: the `setViewport` function actually expects longitude on index 0 and longitude on index 1. Is there something wrong with the naming of the properties?

fix(viewport): move to correct location

---

src/components/Overlay/OverlayDescription/index.js
src/components/Overlay/OverlayTiles/index.js

This PR fixes #151 by using a `1fr` column on small screens instead of a column spanning `minmax(20em, 1fr)`.
@sebastian-meier can you please review if this fixes the issue?

fix(overlay): use single column on small screens

---

src/components/Card/non-verified-mail.tsx

I created an account and saw a bad spelling on the page while waiting for the verify mail. This made me think of directly creating this pull request with proposing the required fixes.
- inserted commas
- corrected Spam-Ordner

Fix typos in non-verified-mail.tsx

---

src/components/Linechart/index.tsx

With scaling 0-300 l/m², the usual rainfall is barely visible in the "rainfall per day" chart. 0-100 l/m² should be more adequate. Average rainfall in Berlin is below 100l/m² per month, so even most heavy rainfall days should be covered (except e.g. 2017 floods with up to 200 l/m², but those are rare cases) while making average amounts more visible. Very light rain is still not visible with 0-100 l/m² scaling, but it's also not that relevant for trees.

Change rainfall chart scaling from 0-300 to 0-100l/m² per day

---

src/components/ButtonWater/index.tsx
src/components/Sidebar/SidebarProfile/index.tsx

And always redirect to home route to close the sidebar.
**Future improvement:** Closing the sidebar should not be done by redirecting to the homepage (Especially important when #215 is implemented, in order not to lose the current tree of sight) but should rather:
A. Be implement within `toggleOverlay`
B. Be implemented  a separate Action `toggleSidebar`  that is triggered as well

#232 - Import toggleOverlay as action instead as state

---

src/__snapshots__/storybook.test.ts.snap
src/components/Sidebar/SidebarTitle/index.tsx
src/components/Sidebar/index.tsx

1. Add `overflow-x: hidden;` and `overflow-y: auto;` on sidebar container
2. Remove hard-coded width of sidebar title (Provoking overflow)
Fixes #253

Fix #253: About sidebar on mobile has an horizontal scrollbar

---

src/__snapshots__/storybook.test.ts.snap
src/components/OpenSource/index.tsx

The image had to be limited to its container. Hardcoded the size of the icon to 16x16px and made
the container a grid container.
This fixes #173

Fix #173: Fix github icon taking up too much vert space on mobile

---

webpack/common.config.js

Which caused the env variable to become undefined

fix(webpack): remove Mapbox key from plugins

---

src/components/TreesMap/DeckGLMap.tsx

This PR fixes the bug that on mobile watered and adopted trees were not displayed when their respective filter was applied.
The bug originates from undefined data being passed into the filter in the `_updateStyles` method which is only called if the device `isMobile`. That's why non-mobile devices were not affected. Their display is handled in a [layer](https://github.com/technologiestiftung/giessdenkiez-de/blob/d426fcc028ad29c6b1b27393ff646e7293877126/src/components/TreesMap/DeckGLMap.tsx#L120) that is not displayed on mobile, see [here](https://github.com/technologiestiftung/giessdenkiez-de/blob/d426fcc028ad29c6b1b27393ff646e7293877126/src/components/TreesMap/DeckGLMap.tsx#L172).
A note was added that indicates where color updates of the circles would be handled for mobile. As this is …

fix(filters): display adopted & watered trees on mobile

---

src/common/interfaces.ts
src/components/TreesMap/DeckGLMap.tsx
src/utils/requests/loadTreesGeoJson.ts

The PR addresses the bug that no trees were displayed when changing the age filter on non-mobile devices (mobile devices were not affected because they pull a different dataset).
The bug was caused by an inexistent key `standalter` that we were trying to assign to our `age` field in the GeoJSON property. The key that **is** existent in the data source is called `age` as well.
The [fix](https://github.com/technologiestiftung/giessdenkiez-de/blob/114740744af19b55f92dcd44f3d732021b9cf5c1/src/utils/requests/loadTreesGeoJson.ts#L33) in this PR is to change the key from `standalter` to `age`. Also, some typing is added, so that confusion is hopefully mitigated in the future.

fix(filter): make tree age filter work

---

src/components/Sidebar/SidebarTree/TreeInfos.tsx
src/components/TreesMap/DeckGLMap.tsx

This PR updates the age filter so that when any age filtering is applied, trees with unknown age disappear. This makes sense from a UX perspective as the user explicitly selects a desired range and may be confused if they see trees without any age in the remaining collection.
Additionally, the displayed individual tree age in the sidebar is adjusted and now calculated by doing `new Date().getFullYear() - parseInt(pflanzjahr, 10)`. This is because the previously used `standalter` value does not seem to be updated anymore and was behind by 2 years. The `pflanzjahr` seems like a more reliable data point here and is now in sync with the actual age and the filter.
---
Note: The filter update is only for non-mobile devices! We use a different vector tile dataset for trees on mobile and trees …

fix(GDK-130): hide trees with unknown age when age filter is applied

---

src/__snapshots__/storybook.test.ts.snap
src/components/DataTable/DataTable.stories.tsx
src/components/DataTable/DataTable.test.tsx
src/components/DataTable/index.tsx
src/components/Tooltip/Tooltip.stories.tsx
src/components/Tooltip/Tooltip.test.tsx
src/components/Tooltip/index.tsx
src/components/TreesMap/DeckGLMap.tsx

This PR updates the tooltip for the pumps. It
- adds a `DataTable` component that can be used for the new tooltip contents (and other things)
- uses `react-map-gl`s own `Popup` for handling user interaction and edge cases such as a tooltip close to the screen edge
- inserts the pump data into the `DataTable` into the `Popup`
---
Note: This PR does not handle tooltips for mobile. They are currently already disabled explicitly. The reason for this should be figured out separately.
Note 2: TypeScript here was hard to handle. ~I had to use an `any` because I couldn't trace back where a type mismatch on the `onHover` originated. Pointers welcome!~
---
Tested on latest macOS and Windows in latest Chrome, Firefox, Edge, Safari (only macOS).
Closes #239

feat(GDK-19): extended tooltip

---

src/assets/MapboxStyleOverrides.ts
src/components/Nav/index.tsx
src/components/TreesMap/DeckGLMap.tsx
src/components/TreesMap/MapTooltip.tsx
src/state/Actions.tsx
src/state/Store.tsx

This PR displays the map controls back into the view. It seems like an update of react-map-gl has messed up the order of display of element. This bug is older and has gone unnoticed for a while. The sidebar, state, for instance, wasn't opening anymore when a button was clicked.

fix(MapControls): Fix hidden map controls

---

.env.sample
create-env.js
src/components/TreesMap/DeckGLMap.tsx
src/utils/requests/loadTreesGeoJson.ts

This PR moves the URLs for the trees data (mobile and desktop) into environment variables.
```
AWS_TREES_URL={AWS_LINK_TO_TREES_AS_CSV}
MAPBOX_TREES_TILESET_URL=mapbox://{username}.{tilesetId}
MAPBOX_TREES_TILESET_LAYER={layer-name-within-tileset}
```

refactor: trees data URLS as env variables

---

src/assets/content.tsx
src/components/App/index.tsx
src/components/ImprintAndPrivacy/index.tsx
src/components/Sidebar/__snapshots__/Sidebar.stories.storyshot

This PR attempts to add the correct OpenStreetMap attribution to the map, as indicated by @joshinils on #330. I followed a combination of the [OSM attribution guideline](https://www.openstreetmap.org/copyright) and the [Mapbox attribution guideline](https://docs.mapbox.com/help/getting-started/attribution/), but I'm not 100% sure if my implementation fulfills your requirements @joshinils. So let me know.
**Edit:** I also added the Mapbox attribution and logo. Now we should be fine.

fix(#330): Add OSM attribution

---

src/components/TreesMap/DeckGLMap.tsx

...when the relevate (Bereits adopted | In den letzten 30 Tagen gegossen) filter is active. Fixes #379 
The problem concerned all trees that were either adopted or watered in the last 30 days and had no age. Ad condition checked whether the tree was within the age range defined by the filter. Now the age range is only checked if the age filter is active.

fix(#379): Fix the bug that ageless watered or adopted trees aren't shown

---

src/index.ejs

To conform to GDPR requirements, this PR disables the use of cookies by Matomo.
Note that analytics with Matomo will still work, it's just anonymized and without the use of cookies. See [the same implementation in Berlin Open Source](https://github.com/technologiestiftung/berlin-open-source-portal/blob/3f9292eda39c65f8f98face3a73a5c65d4a7b431/src/_includes/layouts/root.liquid#L28) for which analytics in Matomo are still available.
-> [Context](https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-without-consent-or-cookie-banner/)

chore(Matomo): do not set cookies

---

src/components/WateringModal/index.tsx

This PR fixes two issues with the watering modal:
- the error message on mobile doesn't change the grid of the inputs
- watering is only allowed as an integer (client-side validation)

fix: watering modal (error CSS + watering only as integer)

---

src/components/ButtonRound/index.tsx
src/components/ButtonWater/index.tsx
src/components/Sidebar/SidebarTree/TreeInfos.tsx

The watering button is arguably more important than the adoption button. That's why this PR changes the order of the buttons.

feat(GDK-116): show watering button first

---

src/components/TreesMap/TreesMap.tsx

This PR makes sure that the trees are rendered with the same pitch as the map. This makes them look more realistic.

fix(GDK-203): use map's pitch also for trees

---

src/assets/Global.tsx
src/common/interfaces.ts
src/components/App/index.tsx
src/components/TreesMap/TreesMap.tsx
src/state/Actions.tsx
src/state/Store.tsx

This PR shortens the initial loading time. We used to have sort of an "artificial" delay because we would only start loading the map once an initial call for **all of community data, adopted data and watered data** had finished.
We don't need this anymore (and potentially we had never needed it). The map component itself now handles the fetching of all the above data and only renders the appropriate layers once the data has been fetched. So, the initial call in `App.tsx` was delaying the map load unnecessarily.
I would suggest we still keep the loading screen, but start loading the map immediately and remove the screen once the map's `onLoad` function was triggered (this is achieved with setting a state `mapHasLoaded` on `onLoad`).

refactor(GDK-207): improve initial loading

---

src/components/TreesMap/TreesMap.tsx
src/utils/requests/getCommunityData.ts

This PR fixes the unresponsive UI that was occurring when the "community data" was busy loading and blocking the main thread. This fix makes the parsing of the community data more efficient by removing the spread syntax.
Note that the frozen UI was only occurring in the production environment because the production database has lots more adopted trees than the development database. To be able to see the difference that this change makes, you will have to locally update your `API_ENDPOINT` variable to use the production API.

refactor(GDK-210): Optimize parsing of community data

---

src/Providers/index.tsx
src/components/AccountEditModal/index.tsx
src/components/Forms/PasswordEditForm/index.tsx
src/components/Modal/index.tsx
src/components/Notification/index.tsx
src/components/PasswordEditModal/index.tsx
src/components/UserCredentials/index.tsx
src/utils/nonPersistentSupabaseClient.ts
src/utils/requests/updatePassword.ts

This PR makes fixes to the action of editing a password.
- we now display all error messages
- we also display a success message in a separate step/view
- we also check that the new password is different from the old one

fix: edit password action

---

src/components/AccountEditModal/index.tsx
src/components/Forms/AccountEditForm/index.tsx
src/components/Notification/index.tsx
src/components/UserCredentials/index.tsx
src/utils/requests/getUsernameBySession.ts
src/utils/requests/updateAccount.ts
src/utils/requests/updateEmail.ts
src/utils/requests/updateUsername.ts
src/utils/requests/validateUsernameUniqueness.ts

This PR refactors the edit account modal. It ensures that all error and success messages are displayed to the user.

refactor: edit account action

---

pages/auth.tsx

This PR prevents the `/auth` route from briefly showing the authenticated state before the user profile appears. We do this by removing the UI and immediately redirecting to `/profile` once there is a session present.
1. Sign out
2. Make sure that no Supabase cookies or localStorage objects are stored in your browser
3. Sign in
You will briefly see the unwanted UI flashing:
After this change, the problem should be gone!

fix: prevent signed-in auth view from flashing

---

.env.sample
.github/workflows/test.yml
src/utils/requests/loadRainGeoJson.ts

Introduces the environment variable "NEXT_PUBLIC_RAIN_DATA_URL". It should contain the address of the rain data geojson file (Usually points to a file within an S3 bucket).
This avoids using a hard-coded address. Now it is possible to inject any url by setting up the hosting environment.
When omitted the Berlin weather data address is used.

adds and uses env var "NEXT_PUBLIC_RAIN_DATA_URL"

---

.github/workflows/test.yml

This PR adds the new env var NEXT_PUBLIC_RECOVERY_AUTH_REDIRECT_URL=${NEXT_PUBLIC_BASE_URL}/auth
to vercel.com and to the test run for documentation purpose.

docs: Added new env var to vercel and test.yml

---

package-lock.json
package.json
test/setup-test-env.js

According to git history this was added for auth0
It also broke all tests locally

test: remove webcrypto modul

---

.env.sample
pages/_app.tsx
src/utils/hooks/useMatomo.ts

This PR adds Matomo tracking (back again). It got lost during the Next.js migration.
---
- https://app.asana.com/0/0/1204577434408291

fix(matomo): Add matomo tracking

---

src/common/database.ts

This PR updates the database types to the latest state. In linked PR we remove the time column from the trees_watered table since we where not using it anymore. Should not affect actions like watering a tree or deleting a watering.
Related to PR
https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/pull/222

chore: Update database types

---

src/components/Sidebar/SidebarTree/TreeInfos.tsx

Not sure if we want to implement this more sophisticated. This was a rather straight-forward approach. Hope I understood the `waterings` and `radolon_days` correctly. 
As requested in https://github.com/technologiestiftung/giessdenkiez-de/issues/475
As documented in https://app.asana.com/0/1204152181784036/1204994173851095

Show water + rain sum in tree side bar

---

.env.sample
src/components/TreesMap/TreesMap.tsx
src/components/TreesMap/osmUtil.ts
src/components/TreesMap/pumpsUtils.ts

We are linking to a version of the theme in our account
and we are using a raw github url with a git hash now
Todos:
Yes we can.

fix(osm): Fix link to mapcomplete tool

---

.github/workflows/rain.yml

Waiting for https://github.com/technologiestiftung/giessdenkiez-de-dwd-harvester/pull/105 to be merged and released first
new env var: `DWD_HARVESTER_VERSION` needs to be set in each environment (i did this already)

chore: update DWD harvester to 2.1.1

---

src/components/TreesMap/TreesMap.tsx

Map zoom was controlled by DeckGL and Map component, which led to weird jumpy behavior. It's now controlled by DeckGL exclusively. Furthermore, I removed some unnecessary minzoom, maxzoom settings.

fix: jumpy zoom

---

src/components/App/index.tsx
src/components/Overlay/OverlayTop/index.tsx
src/components/Switch/index.tsx

- moved language button to fixed top right position
- added styling according to new design on figma
- the language button is currently rendered double in OverlayTop (where it already was) AND in the main App file. Otherwise clicking the language button outside the splash screen would always close the splash screen.
https://app.asana.com/0/1204152181784036/1206565413148089/f

feat: move and style language button

---

src/components/Overlay/index.tsx

fixes the z-index and margin top of overlay (splashscreen):
Before: language switch is over the close button of the overlay, mapbox logo and map imprint links is over the overlay
After: moved the overlay lower down to not clash with language switch, increased z-index of overlay to keep mapbox logo and map imprint links below

fix: z-index of overlay

---

src/components/location-search/location-search.tsx
src/components/navbar/navbar.tsx
src/components/profile/adopted-trees.tsx
src/components/profile/overview.tsx
src/components/profile/profile-details.tsx
src/components/profile/tree-card.tsx
src/components/tree-detail/tree-adopt-card.tsx
tailwind.config.js

we have two defined shadows now:
- shadow-gdk-hard
- and shadow-gdk-soft
I used box-shadow when possible (except for the searchbar, bc of its round shape), because I had some bugs with drop shadow being inherited by other elements.

feat: add shadow and exchange on pages

---

.env.sample
src/auth/auth-store.tsx
src/components/profile/auth-card/auth-card.tsx
src/components/profile/auth-card/forgot-password.tsx
src/components/profile/auth-card/login.tsx
src/components/profile/auth-card/register.tsx
src/components/profile/profile-logged-in/adopted-trees.tsx
src/components/profile/profile-logged-in/overview.tsx
src/components/profile/profile-logged-in/password-reset.tsx
src/components/profile/profile-logged-in/profile-details/edit-email.tsx
src/components/profile/profile-logged-in/profile-details/edit-password.tsx
src/components/profile/profile-logged-in/profile-details/edit-username.tsx
src/components/profile/profile-logged-in/profile-details/profile-details.tsx
src/components/profile/profile-logged-in/profile-logged-in.tsx
src/components/profile/profile-logged-in/tree-card.tsx
src/components/profile/profile.tsx
src/components/profile/validation/email-input-with-validation.tsx
src/components/profile/validation/email-taken-store.ts
src/components/profile/validation/hooks/use-reset-is-email-taken-on-unmount.tsx
src/components/profile/validation/password-input-with-validation.tsx
src/components/profile/validation/username-input-with-validation.tsx
src/components/profile/validation/validation.ts
src/components/profile/validation/warning.tsx
src/components/router/router.tsx
src/error/error-store.tsx
src/i18n/content-types.ts
src/i18n/de.ts
src/i18n/en.ts

fixes/features:
- removed early exits when response object `data` from supabase requests is null and when it is not directly used. In the supabase documentation, there is not defined why or what that means. Before i supposed that might be an error. But now I think we should just stick to make early exits when the `error` object is defined in supabase responses.
- added missing i18n
- added error handling for known/unknown errors in:
- forgot-password submit
- login submit
- register submit
- edit-email submit
- edit-username submit
- edit-password click
- change-password submit
- username-input-with-validation change
- i was getting confused the enable/disable conditions when editing email/username and tried to make the naming clearer
- made error messages isEmailTaken reset on component …

feat: finished registration use-case and fixed linting errors

---

src/components/tree-detail/tree-detail.tsx
src/components/tree-detail/tree-water-need-unknown.tsx
src/components/tree-detail/tree-water-needs.tsx
src/components/tree-detail/watering-dialog.tsx

Previously, two network requests to "lastwatered" endpoint were made when tree detail view was opened, although only one is necessary.

fix: too many last watered requests on tree click

---

src/components/buttons/primary.tsx
src/components/buttons/secondary.tsx
src/components/filter/filter-switch.tsx
src/components/filter/filter.tsx
src/components/filter/tree-age-button.tsx
src/components/location-search/location-search.tsx
src/components/router/router.tsx

- On real mobile, the viewport was wrong
- and the filter did not fit on the screen.
- clear icon is now shown only when search string is not empty
TIL
> [Dynamic viewport height](https://tailwindcss.com/docs/height#dynamic-viewport-height)
Use h-dvh to make an element span the entire height of the viewport, which changes as the browser UI expands or contracts.

fix: viewport mobile, filter mobile, clear icon

---

src/components/Switch/index.tsx

Fix issue for mobile. Language toggle covers close button when opening Bauminformation.

fix: change z index of language toggle

---

src/components/map/hooks/use-map-trees-interaction.tsx

this allows the zoom in after clicking on an adopted tree in profile

feat: zoom in to tree when map loaded

---

src/components/buttons/secondary.tsx
src/components/profile/profile-alert/alert-dialog.tsx
src/components/tree-detail/hooks/use-fetch-tree-data.tsx
src/components/tree-detail/hooks/use-water-tree.tsx
src/components/tree-detail/watering-dialog.tsx

I replaced the controlled inputs with a form to have some basic validation, e.g. water amount >= 1, date <= today. I also added a numeric input mode for easier input on mobile:
---
- https://app.asana.com/0/0/1206727518885048

fix: replace controlled inputs in watering dialog with form

---

src/components/tree-detail/hooks/use-water-tree.tsx

use username from store instead of signup_username from user metadata

fix: use correct username when watering a tree

---

src/components/location-search/hooks/use-geocoding.tsx
src/components/location-search/location-search.tsx

remove argument from use-geocoding hook call and move to fetch geocoding results call to prevent that the fetch gets called with the previous value instead of the current value
---
- https://app.asana.com/0/0/1206979616697418

fix: remove argument from use-geocoding hook call

---

src/components/map/hooks/use-map-pumps-interaction.tsx

I added map.once("idle"
which fires when everything has been rendered on the map.
I kept map.isStyleLoaded() to avoid a long loading state for the pumps, when only the pumps are toggled. 
So either the pump layer is set to visible if the style is loaded quickly enough otherwise the pumps are set to visible when the idle state is reached.
---
- https://app.asana.com/0/0/1206980650488442

feat: add listener for map idle

---

src/components/tree-detail/last-waterings/watering-card.tsx

delete watering button makes tree info x scrollable

fix: change delete watering button to hidden

---

src/components/tree-detail/tree-water-needs/watering-dialog.tsx

replace close (which closes the tab) function with closeWateringDialog (introduced in previous refactoring)
---
- https://app.asana.com/0/0/1207063581751692

fix: replace close function with closeWateringDialog

---

src/components/tree-detail/stores/adopt-tree-store.tsx
src/components/tree-detail/tree-adopt-card.tsx
src/i18n/content-types.ts
src/i18n/de.ts
src/i18n/en.ts

There was a bug showing the label `also adopted by others` when the user was the sole adopter of a tree.
This PR fixes this and hides this label when the user is the sole adopter of a tree. Also refactored a few names in an attempt to bring more clarity.

fix: hide also adopted by others when the only adopter is the user themself

---

src/components/anchor-link/internal-anchor-link.tsx
src/components/profile/profile-logged-in/adopted-trees/adopted-trees-card.tsx

align section title and link to adopted trees

feat: align section title and link to adopted trees

---

src/components/filter/age-range-slider/bar-graph.tsx
src/components/filter/age-range-slider/hooks/use-bar-graph-height.tsx
src/components/router/router.tsx

~adding webkit-overflow-scrolling to filter view to fix the bug where you could not scroll the filter view on mobiles with very small height~
~edit: is just a test / draft needs to be approved from PO~
this PR now makes the bar chart change its height depending on the viewport height

fix: barchart height

---

src/components/map/hooks/use-map-constants.tsx
src/components/map/hooks/use-map-trees-interaction.tsx

https://app.asana.com/0/home/1204602906499599/1207209277737795

fix: no offset on mobile

---

src/components/map/hooks/use-map-trees-interaction.tsx

fixes the bug on mobile, when you pinch to zoom, the map jumps sometimes a bit around on zoom end. This is because zoomend used to only set the zoom in the state. However, mapbox can zoom+pan at the same time, which means that using pinch to zoom also slightly moves the center of the map, which then gets not updated correctly in the state

fix: jumpy map after zoom

---

src/components/router/store.tsx

added debounce when writing to url, this prevents the error SecurityError: Attempt to use history.pushState() more than 100 times per 10 seconds which crashes the website

feat: add debounce when writing to url

---

.github/CODEOWNERS
.github/workflows/rain.yml
src/components/map/hooks/use-tree-circle-style.tsx
src/components/tree-detail/hooks/use-tree-age-classification.tsx
src/tests/unit/baby-tree-water-needs-special-district.test.ts
src/tests/unit/senior-tree-water-needs-special-district.test.ts

https://app.asana.com/0/1204152181784036/1208351541946150
needs https://github.com/technologiestiftung/giessdenkiez-de-dwd-harvester/pull/135
For testing, use these tree ids:
Mitte:
- 00008100:00150353 -> 12 years, covered by district
- 00008100:0014f6e0 -> 13 years, covered by groundwater
Pankow:
- 00008100:0028fbd8 -> 11 years, covered by district
- 00008100:002e51c0 -> 12 years, covered by groundwater
Neukölln:
- 00008100:00288b4f -> 9 years, covered by district
- 00008100:0022e9d6 -> 10 years, covered by groundwater
Lichtenberg:
- 00008100:001ff320 -> 12 years, covered by district
- 00008100:001fe1d2 -> 13 years, covered by groundwater

feat: age classification per district

---

src/i18n/de.ts
src/i18n/en.ts

- Updated the number of Berlin street trees from 885,825 to 967,365 in both German and English files, reflecting the latest data as of March 2025.

fix(i18n): update tree count and improve wording in German and English translations
