technologiestiftung/giessdenkiez-de

auth0_config.json, create-env.js, index.js
- creates .env vars file on netlify with needed envs
- removes auth0_config.json
- (still needs change of tenant in trees api depends on https://github.com/technologiestiftung/tsb-tree-api-now-express/pull/2)
=> setup(auth0): Adds a new tenant for auth0

readme.md
=> Chore/housekeeping README

src/assets/content.js
=> fix: change title wording in sidebar

src/components/Credits/index.js, src/components/Sidebar/SidebarAbout/index.js
=> feat: more visible Förderlogo

package-lock.json, package.json, src/components/Sidebar/SidebarAbout/index.js, src/components/SocialSharing/index.js
This PR creates social sharing buttons in the sidebar. Currently Facebook and Twitter.
Fixes #5
=> feat: social sharing buttons

create-env.js, package-lock.json, src/components/Card/CardProgress/index.js, src/components/Legend/index.js, src/components/Nav/index.js, src/components/Sidebar/SidebarAbout/index.js, src/components/Sidebar/SidebarProfile/index.js
This PR
Adds:
Connection to Auth0 Management Api (through https://tsb-trees-api-user-management.now.sh/api source is https://github.com/technologiestiftung/tsb-trees-api-user-management)
- feature Button for deleting the user account on 
- Example code to get user data from the auth0 managment api
- Env variable for the url of the api
Fixes:
- Error about missing keys in Legend and CardProgress
Chore:
- some prettier formatting
fixes #35 
re #31 
re #49
=> the right to be forgotten

src/components/Credits/index.js
=> fix: credits order and wording

src/index.ejs
fix #89 
@fdnklg this should fix the last flash
=> fix(loading screen): adds text property to loading label in index.ejs

src/index.ejs, webpack/dev.config.js
This PR adds:
- css in index.ejs to fade in the whole body. Prevents flicker from font fix #120 
- webpack config to create chunks on dev mode and write them to disk. Makes development faster close #118
=> Feautre fade in body

src/assets/content.js
This PR updates some info texts (in the overlay and sidebar) with texts from the content doc.
Fixes #125
=> content: update info texts

src/assets/content.js
This PR only changes the wording of one of the on-load notes.
Fixes #124
=> fix: on-load wording

src/components/Overlay/OverlayBeta/index.js, src/components/Overlay/OverlayTop/index.js
This PR adds an indicator that shows the project is still in beta.
Fixes #130
=> feat: add beta note to overlay

.eslintrc.js, src/components/map/index.js, src/utils/index.js, src/utils/utils.test.js
Before we can add Geolocation to the project we really need to test this on several devices.
Seems to work on
- FFfox (latest)
- Chrome (latest)
- Safari (latest)
Creates problems on Mobile iOS Safari
=> disable Geolocation

src/components/map/index.js, src/utils/index.js
Apparently DWD 1 is not 1ml but 0.1ml
We could change this in the database, but this would mean, transferring 625.000 "," characters, therefore, changing it client-side makes more sense.
=> fix dwd scale

src/components/Card/CardLegend/index.js, src/components/Sidebar/SidebarSearch/SidebarSearchLocation.js
I added a custom location search to the sidebar. The geolocator from the mapbox react module was acting all weird. Search entry > 3 creates a result list of up to 5 results. On click the viewport state is changed and the map transitions to the location.
The whole component is pretty much isolated, it does not bind to any values and only sets the viewport on click.
=> Feature locationsearch

package-lock.json, package.json, src/components/map/ChorolethLayer.js, src/components/map/index.js, src/state/Actions.js, src/state/Store.js
Through `react-device-detect` we detect if its a mobile device. For mobile a few customisations were implemented:
- Trees are visualised through vectortiles (zoom < 11 is not possible) from mapbox
- Interactions for selections and layer-toggling are adopted to vectortiles
The non-mobile version has not been changed.
=> Feature vectortiles

src/index.ejs, webpack/common.config.js
=> Matomo tracking

.gitignore, src/index.ejs
=> fix(language): change html lang attribute to de

src/components/Card/index.js, src/components/Linechart/index.js, src/components/map/index.js, src/state/Actions.js, src/utils/index.js
This PR fixes some more values where the radolan_sum was out of scale. Realted to 
#141 #140
=> Linchart sidebar ticks scale fixes

src/assets/content.tsx
please review and merge if ok 
@dnsos
=> spellcheck: typo & wording fixes

src/components/Overlay/OverlayDescription/index.tsx, src/components/imprint-and-privacy.tsx
This PR takes care of some accessibility requests, and fixes #186.
It:
- increases the font size of the overlay description
- increases the opacity of the imprint and privacy links
=> fix: more accessible text

src/assets/content.tsx, src/components/Overlay/OverlayEvent/index.tsx, src/components/Overlay/OverlayTop/index.tsx
due to our upcoming Event on the 11th September, I added an eventNote to the overlay to get users attracted to particiapte. After the event, eventNote will be removed again.
=> added eventNote to overlay

README.md, src/components/map/index.tsx
new features in basemap: house numbers, public transport, coloring
close #229
=> replace basemap

src/components/Card/CardAccordion/TreesAdopted.tsx, src/components/Card/CardProgress/index.tsx, src/components/Legend/Legend.tsx, src/components/Overlay/OverlayTiles/index.tsx, src/components/Sidebar/SidebarAbout/index.tsx, src/components/Sidebar/SidebarAdopted/index.tsx, src/components/Sidebar/SidebarSearch/SidebarSearchLocation.tsx
Using i as key is not good. Actually it is pretty bad practice.
It might mess up the order of components.
See https://reactjs.org/docs/lists-and-keys.html#keys
=> fix: Unpropper usage of key equals index

.env.sample, README.md, create-env.js, src/components/Sidebar/SidebarSearch/SidebarSearchLocation.tsx, src/components/map/index.tsx
Add .env.sample and mention in docs and also renamed API_KEY to MAPBOX_API_KEY
This is a continuation of #302. This fixes #302
=> docs(env): Add .env.sample and mention in docs

src/components/ButtonWater/index.tsx
"Bewässerung wir eingetragen" -> "Bewässerung wird eingetragen"
=> fix(GDK-98): fix typo in watering button

.github/workflows/test.yml
Remove the anchor 'watchPaths'
=> fix: Anchors are not currently supported.

src/components/Legend/MapLayersLegend.tsx
As requested in the user testing.
=> fix(GDK-121): collapse legend by default (mobile)

src/__snapshots__/storybook.test.ts.snap, src/assets/content.tsx, src/components/Overlay/OverlayTop/index.tsx, src/components/TreesMap/DeckGLMap.tsx, src/utils/requests/loadTreesGeoJson.ts
This PR adds a news section announcing the new trees data in the welcome overlay.
It also updates the amount of trees from 625.000 to 750.000.
> Hint: Do not merge before new database is in production.
=> feat(News): announce new trees data

.github/workflows/pumps.yml, .github/workflows/rain.yml
Allows running all cronjobs from pipedream
=> feature(cronjobs): Adds repository workflow dispatch [skip ci]

package-lock.json
According to #257 this PR updates the browserlist with the command `npx browserslist@latest --update-db`
=> fix(#257): Update browserlist

package-lock.json, src/index.ejs
This PR brings the latest changes of `staging` into `master`, namely only the disabling of Matomo cookies (#401)
=> Merge staging to master (disable Matomo cookies)

src/assets/content.tsx, src/components/Overlay/__snapshots__/Overlay.stories.storyshot
This PR fixes 3 typos in the intro modal.
=> Staging to Master (typo fixes)

src/components/Overlay/OverlayTop/index.tsx
This PR removes the banner for the maintenance period.
Closes #528
=> chore: inform about end of maintenance period

src/assets/content.tsx, src/components/Overlay/OverlayTop/index.tsx
Adds an announcement about the upcoming DNS/Nameserver maintenance period
=> chore: Add announcement about DNS changes

src/assets/content.tsx
Since we every now and then need to use this section I would prefer to keep it in the source. instead of writing it new every time. What do you think @dnsos @vogelino
=> chore: Remove whats new section in content

src/mocks/handlers.ts, src/utils/requestUtil.ts, src/utils/requests/adoptTree.ts, src/utils/requests/getCommunityData.ts, src/utils/requests/getTreeData.ts, src/utils/requests/getTreesAdoptedByUser.ts, src/utils/requests/getTreesByIds.ts, src/utils/requests/getUserWaterings.ts, src/utils/requests/getWateredTrees.ts, src/utils/requests/isTreeAdopted.ts, src/utils/requests/unadoptTree.ts, src/utils/requests/unwaterTree.ts, src/utils/requests/waterTree.ts
BREAKING CHANGE: This URLs are not compatible with the old api.
They only work with the supabase version which is also a PR here:
https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/pull/186
Frontend is also deployed here https://supabase.giessdenkiez.de
=> feat(supabase): Update URLs to match new API

src/utils/requests/getCommunityData.ts
In the old version of the API we had to parse strings to numbers
now we have real numbers
=> fix(community data): Response has real numbers

.github/workflows/pumps.yml
This PR updates the commit action for the pumps to its latest version
=> ci: Update commit action to latest

src/assets/content.tsx
This PR updates the overlay to represent the current state of migration
=>  chore(overlay): Update whats new text

src/assets/content.tsx
Adds some infos about the current state of the migration to the overlay
=> chore(overlay): Update whats new text

README.md
=> chore(readme): Remove deprecated repo links

.github/workflows/rain.yml
Also changed Github environment secrets to reflect the new variable name.
=> Use latest DWD Harvester v2.1.0

src/components/Sidebar/SidebarTree/TreeInfos.tsx
feat(tree): show water + rain sum of last 30 days in tree sidebar
=> Show water + rain sum in tree side bar (#610)

.github/workflows/rain.yml
v2.1.1 is working, we can use it for prod
=> chore: use dwd harvester v2.1.1 for all environments

package-lock.json, package.json, src/components/TreesMap/TreesMap.tsx
Geolocate works again. However, before there was a property `transitionDuration: VIEWSTATE_TRANSITION_DURATION` to make the transition/animation slower, which does not work anymore:
- Using this property results in two transitions. 
- Removing this property makes the transition/animation very fast. 
I could not fix it yesterday. My suggestion would be to merge it as is and work on the prioritized features, and put this issue in the backlog to discuss/fix it later.
=> chore: updated react-map-gl library and its usage

src/components/TreesMap/TreesMap.tsx
Once again a dirty hack. Maybe there is a cleaner way? The reason why we need to do it is because we are using DeckGL and react-map-gl components and they fight for who sets the zoom. Without the `target` check to find out from where the zoom event comes from the zoom will be jumpy / flickering when zooming manually. 
Maybe we don't even need DeckGL? But this is a bigger topic.
=> fix: zoom via controls

src/components/ButtonRound/index.tsx, src/components/ExpandablePanel/index.tsx, src/components/Forms/AccountEditForm/index.tsx, src/components/Forms/Buttons/ButtonSubmitRound.tsx, src/components/Forms/PasswordEditForm/index.tsx, src/components/Legend/LegendFlexBoxes.tsx, src/components/Legend/MapLayersLegend.tsx, src/components/MapLayout.tsx, src/components/Nav/index.tsx, src/components/Sidebar/SidbarWrapper.tsx, src/components/Sidebar/Sidebar.stories.tsx, src/components/Sidebar/SidebarAbout/index.tsx, src/components/Sidebar/SidebarClose/index.tsx, src/components/Sidebar/SidebarProfile/index.tsx, src/components/Sidebar/SidebarSearch/SidebarSearchLocation.tsx, src/components/Sidebar/SidebarSearch/index.tsx, src/components/Sidebar/SidebarTree/TreeInfos.tsx, src/components/SquareButton/SquareButton.test.tsx, src/components/SquareButton/index.tsx, src/components/TreesMap/TreesMap.tsx, src/components/UserCredentials/index.tsx
Fixed some errors:
- changed many styled components props to transient props (e.g.: isActive -> $isActive) (docs: https://styled-components.com/docs/api#transient-props), removed some unused props
- removed `StyledLink` inside `Link` components (from nextjs) to prevent nested a-tags (currently renders something like this `<a><a>...</a></a>`), and moved the styling of the `StyledLink` to the `Link` component.
- added some missing types
=> fix: some errors

.github/workflows/rain.yml
this is needed to fix the "black trees on map" bug by using a newer version of DWD harvester, see here: https://github.com/technologiestiftung/giessdenkiez-de-dwd-harvester/pull/115
=> chore: update dwd version

src/assets/content.tsx, src/components/Credits/index.tsx, src/components/Overlay/OverlayBottom/index.tsx, src/components/Overlay/OverlayDescription/index.tsx, src/components/Overlay/index.tsx, src/components/Switch/index.tsx, src/utils/matomo.ts
- add salespages banner to home splash screen
- fixed typos and localized content for the banner
- move matomo tracking function to utils
=> feat: add salespages link to home splash screen

package-lock.json, package.json, src/App.tsx, src/components/matomo/hooks/use-track-page-view.tsx, src/components/router/hooks/use-location-event-listener.tsx, src/components/router/router.tsx, src/components/router/search.tsx, src/components/router/store.tsx, src/main.tsx, vercel.json
feat: first draft of routing, state management + examples
I also updated matomo tracking, i deleted the track page hook and added the track page call inside the `setPathname`
=> feat: first draft of routing, state management + examples

src/components/location-search/location-search.tsx
=> fix: input grow on location search

.env.sample, src/components/icons/info-icon.tsx, src/components/location-search/location-search.tsx, src/components/map/hooks/use-circle-paint.tsx, src/components/map/hooks/use-hovered-tree.tsx, src/components/map/hooks/use-map-constants.tsx, src/components/map/hooks/use-map-interaction.tsx, src/components/map/hooks/use-map-setup.tsx, src/components/map/hooks/use-selected-tree.tsx, src/components/navbar/navbar.tsx, src/components/router/store.tsx
- map interaction hook enables hover/click feature
- tree circle styling
- treeId as url search param on click (in preparation for tree detail view)
=> feat: map interaction and tree hover/click

public/images/icon-locate.svg, public/images/icon-zoom-in.svg, public/images/icon-zoom-out.svg, src/components/map/hooks/use-map-setup.tsx, src/components/map/map-attribution.tsx, src/components/map/map.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts, src/index.css
added mapbox controls and overwrote mapbox styles
=> feat: add mapbox controls

.env.sample, src/components/info/credits.tsx, src/components/info/info.tsx, src/components/info/qa-entry.tsx, src/components/location-search/location-search.tsx, src/components/map/hooks/use-map-constants.tsx, src/components/map/hooks/use-map-interaction.tsx, src/components/map/hooks/use-map-setup.tsx, src/components/router/router.tsx, src/components/tree-detail/hooks/use-adopt-tree.tsx, src/components/tree-detail/hooks/use-tree-age-classification.tsx, src/components/tree-detail/hooks/use-water-tree.tsx, src/components/tree-detail/tree-adopt-card.tsx, src/components/tree-detail/tree-detail.tsx, src/components/tree-detail/tree-water-need-unknown.tsx, src/components/tree-detail/tree-water-needs.tsx, src/components/tree-detail/water-progress-circle.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts, src/tests/unit/baby-tree-water-needs.test.ts, src/tests/unit/grownup-tree-water-needs.test.ts, src/tests/unit/junior-tree-water-needs.test.ts, src/tests/unit/senior-tree-water-needs.test.ts, src/tests/unit/unknown-tree-water-needs.test.ts
feat:
- logos in about us
fixes:
- initial zoom, min zoom, location zoom
- baby trees can't be watered and adopted
- no circle visual for senior trees
- age calculation
- report problem text
- prevent requests to authed routes when user not logged in
=> feat: logos in about us, fix: various fixes

src/components/info/info.tsx, src/components/navbar/navbar.tsx, src/components/profile/profile-logged-in/password-reset.tsx, src/components/profile/profile-logged-in/profile-logged-in.tsx, src/components/profile/profile.tsx, src/components/router/languageToggle.tsx
Desktop: the language toggle is on the navbar at the bottom left
mobile: the toggle is only visible in profile and info view always at the top right aligned on the right side of the headline
---
- https://app.asana.com/0/0/1206746728905385
=> feat: add lang toggle with css for responsive position

src/components/profile/profile-logged-in/profile-logged-in.tsx, src/components/router/languageToggle.tsx
task:
https://app.asana.com/0/1204152181784036/1206746728905385
=> fix: language toggle position for mobile

src/app.tsx, src/components/anchor-link/external-anchor-link.tsx, src/components/anchor-link/internal-anchor-link.tsx, src/components/map/map-attribution.tsx, src/components/profile/auth-card/forgot-password.tsx, src/components/profile/auth-card/login.tsx, src/components/profile/auth-card/register.tsx, src/components/profile/profile-logged-in/overview.tsx, src/components/profile/profile-logged-in/password-reset.tsx, src/components/profile/profile-logged-in/profile-details/delete-account-dialog.tsx, src/components/profile/profile-logged-in/profile-details/profile-details.tsx, src/components/profile/profile-logged-in/profile-logged-in.tsx, src/components/profile/profile-logged-in/tree-card.tsx, src/components/profile/validation/email-input-with-validation.tsx, src/components/router/router.tsx, src/components/router/store.tsx, src/components/tree-detail/problem-card.tsx, src/components/tree-detail/tree-detail.tsx, src/tests/e2e/auth/_setup.test.ts
added styled internal and external anchor links (for blue semibold with hover effect anchor links). Some anchor links (icon links, map attribution, nav links) are styled differently, they remain untouched.
=> feat: add styled internal and external anchor links

src/components/profile/profile-logged-in/profile-details/delete-account-dialog.tsx, tailwind.config.js
added a new blur `xs` tailwind class and used it instead of `sm`, also used the default gdk-shadow
=> feat: reduce blurriness on account delete modal backdrop

src/components/icons/clear-icon.tsx, src/components/icons/search-icon.tsx, src/components/location-search/location-search.tsx
https://app.asana.com/0/1204152181784036/1206552548484992
- stroke width of search and clear icon
- border radius of search suggestions
=> feat: adjust styling for searchbar

src/components/profile/profile-logged-in/tree-card.tsx
https://app.asana.com/0/1204152181784036/1206727518884838
=> feat: update styling for tree card

templates/email/change-email-address.html, templates/email/confirm-signup.html, templates/email/reset-password.html
updated supabase e-mail templates
---
- https://app.asana.com/0/0/1206876487230962
=> feat: update supabase e-mail templates

templates/email/change-email-address.html, templates/email/confirm-signup.html, templates/email/reset-password.html
replaced = with * in email templates
=> feat: replaced = with * in email templates

src/components/buttons/adoptButton.tsx, src/components/profile/profile-logged-in/adopted-trees/tree-card.tsx, src/components/tree-detail/hooks/use-adopt-tree.tsx, src/components/tree-detail/hooks/use-fetch-tree-data.tsx, src/components/tree-detail/tree-adopt-card.tsx, src/components/tree-detail/tree-detail.tsx, src/components/tree-detail/water-progress-circle.tsx, src/i18n/en.ts
- fix: adopt tree refresh
- fix: i18n reactiveness
- fix: english translations
=> fix: adopt tree refresh + i18n fixes

src/i18n/de.ts, src/i18n/en.ts
add non-breakable white spaces to map attribution improve label
=> feat: add non-breakable white spaces to map attribution improve label

tailwind.config.js
based on: https://benjamincrozat.com/disable-hover-styles-mobile-tailwind-css
=> feat: only react to hover on supported devices

src/components/buttons/tertiary.tsx, src/components/tree-detail/tree-water-need-unknown.tsx, src/components/tree-detail/tree-water-needs.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
- replaced water need info box with collapsible card
- updated translations
=> feat: replaced water need info box with collapsible card

src/components/buttons/secondary.tsx, src/components/buttons/tertiary.tsx, src/components/tree-detail/tree-water-need-unknown.tsx, src/components/tree-detail/tree-water-needs.tsx, src/components/tree-detail/watering-dialog.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
- added disabled button I watered button when logged out
- added required attribute to watered amount and date inputs
- added onclick listener to close dialog when clicking in the background
=> Feat/add prompt suggesting to log-in to water

src/components/tree-detail/watering-dialog.tsx, src/index.css
added x button to close watering dialog
=> feat: add x button to close watering dialog

src/components/icons/heart-icon.tsx, src/components/profile/profile-logged-in/adopted-trees/adopted-trees.tsx, src/components/profile/profile-logged-in/adopted-trees/tree-card.tsx
[https://app.asana.com/0/1204152181784036/1206727518884838](https://app.asana.com/0/1204152181784036/1206727518884838)
=> feat: adjust heart position and skeleton size

src/components/profile/profile-logged-in/overview.tsx, src/components/skeleton/skeleton.tsx
[https://app.asana.com/0/1204152181784036/1206727518884838](https://app.asana.com/0/1204152181784036/1206727518884838)
=> feat: adjust styling for profile overview

src/components/buttons/secondary-destructive.tsx, src/components/profile/profile-logged-in/profile-details/delete-account-dialog.tsx
[https://app.asana.com/0/1204152181784036/1206979616697416](https://app.asana.com/0/1204152181784036/1206979616697416)
=> feat: change order of buttons on mobile and small css fix

src/components/router/router.tsx, src/components/splash/splash.tsx, src/components/tree-detail/tree-water-needs/watering-dialog.tsx
---
- https://app.asana.com/0/0/1206979615446458
=> feat: close splash on click outside WIP

src/components/map/hooks/use-map-setup.tsx
---
- https://app.asana.com/0/0/1206939171998532
=> feat: remove live location updates when a user locates themself

src/components/map/hooks/use-map-constants.tsx, src/components/map/hooks/use-map-trees-interaction.tsx
+ a little offset so that the tree looks centered
=> fix: zoom to tree on page reload

src/components/profile/profile-logged-in/password-reset.tsx, src/components/profile/profile-logged-in/profile-logged-in.tsx, src/tests/e2e/auth/forgot-password.test.ts
- added error handling on password-reset
- removed deprecated parts in profile-logged-in
=> fix: added error handling on password-reset, removed deprecated parts

package-lock.json, package.json, src/components/info/credits.tsx, src/components/info/info.tsx, src/components/info/qa-entry.tsx, src/components/splash/splash.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
* feat: reposition logos on splash screen
* feat: small adjustments to splash logo positions
* feat: restructure about page with logos
* feat: about english text update
* feat: max size for logo on info page on big screens
=> Feat/change logo position (#843)

src/components/info/info.tsx, src/components/profile/profile-logged-in/profile-logged-in.tsx
tasks:
[https://app.asana.com/0/1204152181784036/1207065545100695
](https://app.asana.com/0/1204152181784036/1207065545100695)
[https://app.asana.com/0/1204152181784036/1207065545100689](https://app.asana.com/0/1204152181784036/1207065545100689)
=> feat: adjust title position of Profile and info border radius

src/components/map/map-attribution.tsx
task:
[https://app.asana.com/0/1204152181784036/1207113644394509](https://app.asana.com/0/1204152181784036/1207113644394509)
=> feat: change attribution to light gray and underlined

src/components/profile/auth-card/login.tsx, src/components/tree-detail/tree-adopt-card.tsx, src/components/tree-detail/tree-water-needs/tree-water-need-unknown.tsx, src/components/tree-detail/tree-water-needs/tree-water-needs.tsx
task: [https://app.asana.com/0/1204152181784036/1204153176071406](https://app.asana.com/0/1204152181784036/1204153176071406)
=> feat: redirect to tree after logging in from tree info link

src/i18n/de.ts, src/i18n/en.ts, src/tests/e2e/auth/constants.ts, src/tests/e2e/auth/edit-user.test.ts, src/tests/e2e/auth/utils.ts
(includes tests for change of double confirmation on email change to single confirmation)
---
- https://app.asana.com/0/0/1207053193491974
=> chore: add tests for edit-user features

src/components/tree-detail/stores/adopt-tree-store.tsx, src/components/tree-detail/tree-adopt-card.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
make adoptedByOthers visible for non logged-in users in tree detail view
---
- https://app.asana.com/0/0/1207053193491978
=> feat: make adoptedByOthers visible for non logged-in users in tree detail view

src/components/alert-dialog/alert-dialog.tsx, src/components/profile/auth-card/forgot-password.tsx, src/components/profile/auth-card/register.tsx, src/components/profile/profile-logged-in/password-reset.tsx, src/components/profile/profile-logged-in/profile-details/edit-email.tsx, src/components/profile/profile-logged-in/profile-details/edit-password.tsx, src/components/tree-detail/hooks/use-water-tree.tsx, src/components/tree-detail/tree-water-needs/watering-dialog.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
- refactor alert-dialog component to main components folder since it is used outside of profile
- show dialog for 2 sec after watering was successful
task: [https://app.asana.com/0/1204152181784036/1207053193491980](https://app.asana.com/0/1204152181784036/1207053193491980)
=> feat: show alert after successful watering

public/images/icon-water-large.svg, src/components/splash/splash.tsx
task: [https://app.asana.com/0/1204152181784036/1207077194499976](https://app.asana.com/0/1204152181784036/1207077194499976)
I kept the height responsive for XL size (1024-1280px), since it varies a lot within the range
=> feat: make german and english version same height from xl size on

src/auth/auth-store.tsx, src/components/icons/error-icon.tsx, src/components/profile/profile-logged-in/password-reset.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts, src/tests/e2e/auth/forgot-password.test.ts
---
- https://app.asana.com/0/0/1207077849457916
=> fix: add password-recovery protection for reset-password page

src/components/anchor-link/internal-anchor-link.tsx, src/components/profile/profile-logged-in/adopted-trees/adopted-trees-card.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
add link to highlight/filter my adopted trees on the map on in the profile -> adopted trees section
---
- https://app.asana.com/0/0/1207132261291428
=> feat: add link to highlight/filter my adopted trees on the map 

src/components/router/router.tsx, src/components/splash/splash-store.tsx, src/components/splash/splash.tsx
This PR hides the splash screen for a week after closing it
---
- https://app.asana.com/0/0/1207010784875414
=> feat: hide splash screen for a week after closing it

.github/workflows/e2e-tests.yml
=> ci: forbid e2e tests to renovate

src/components/tree-detail/tree-detail.tsx
keep previously selected tree highlighted after closing tree details
---
- https://app.asana.com/0/0/1207209277737851
=> feat: keep previously selected tree highlighted after closing tree details

.github/workflows/rain.yml
* fix: env in actions
* fix: env
* fix: env
* fix: env
* fix: env in outputs
* fix: syntax
* fix: do not dynamically set version
* fix: separate jobs
* fix: revert
* fix: version
* fix: only set environment
* fix: name
=> fix: vars in github action (#912)

.github/workflows/rain.yml, src/components/map/hooks/use-map-trees-interaction.tsx, src/components/profile/profile-logged-in/adopted-trees/adopted-trees.tsx, src/components/tree-detail/hooks/use-tree-age-classification.tsx, src/components/tree-detail/tree-adopt-card.tsx, src/components/tree-detail/tree-age.tsx, src/components/tree-detail/tree-types.ts, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts, src/tests/unit/baby-tree-water-needs.test.ts, src/tests/unit/junior-tree-water-needs.test.ts, src/tests/unit/senior-tree-water-needs.test.ts, src/tests/unit/unknown-tree-water-needs.test.ts
* fix: tree age calculation
* fix: tests
* fix: fallback for tree type unknown
=> fix: prepare for db changes (tree age, lat, lng) (#915)

src/components/alert-dialog/warning-dialog.tsx, src/components/icons/mail-icon.tsx, src/components/tree-detail/last-waterings/watering-card.tsx, src/components/tree-detail/last-waterings/watering-section.tsx, src/components/tree-detail/tree-water-needs/contact-dialog.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts, src/shared-stores/selected-contact-recipient-store.tsx
needs https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/pull/265
=> feat: contact request

src/components/icons/spinner-icon.tsx, src/components/tree-detail/last-waterings/watering-card.tsx, src/components/tree-detail/tree-water-needs/contact-dialog.tsx, src/i18n/content-types.ts, src/i18n/de.ts, src/i18n/en.ts
needs https://github.com/technologiestiftung/giessdenkiez-de-postgres-api/pull/267
=> feat: check contact request before showing dialog

src/components/tree-detail/last-waterings/watering-card.tsx, src/components/tree-detail/tree-water-needs/contact-dialog.tsx
seems like some edge function errors (like 502 maybe) are not caught properly, reported in https://app.asana.com/0/1204152181784036/1208351541946154
=> feat: catch edge function errors

package-lock.json, package.json
renovate bot merged broken deps into staging automatically, see https://github.com/technologiestiftung/giessdenkiez-de/pull/958 although itself warned:
> You probably do not want to merge this PR as-is.
=> fix: broken deps (bad renovate bot)

src/components/navbar/navbar.tsx
---
- https://app.asana.com/0/0/1208997938026218
=> Feat: switch navigation order

src/i18n/en.ts
before was a wrong copy/pasta, now should be correct
=> feat: update wording for the 2025 trees update - part 2
